### PR TITLE
Feature/upgrade.yaml

### PR DESCRIPTION
**Pull request by Vafilor**

### CODE REVIEW

**Comment by rushtehrani** [comment]
Looks like the new package is using 4 spaces instead of 2 spaces now:
image

**Comment by Vafilor** [comment]
That's fixable, should be an encoder setting. Let me take a look

**Comment by Vafilor** [comment]
@rushtehrani Pushed up a fix.

**Comment by rushtehrani** [comment]
Cool, spacing is good now. Any idea why ordering changed (right side is the old ordering)?
image

**Comment by Vafilor** [comment]
@rushtehrani I'm not sure about why the ordering changed. My guess it because of internal changes? I could do a sort on the data to ensure it's consistent.

**Comment by rushtehrani** [comment]
> @rushtehrani I'm not sure about why the ordering changed. My guess it because of internal changes? I could do a sort on the data to ensure it's consistent.

It looks like the older version was alphabetical, ideally we keep it the same.

**Comment by Vafilor** [comment]
@rushtehrani Roger, will adjust.

**Comment by Vafilor** [comment]
@rushtehrani Pushed up a fix to make it alphabetical, can you see if it looks good on your end?

**Pull request merged**
